server:
  port: ${PORT:8080}

spring:
  # config:
  #   import: optional:file:.env[.properties]
  devtools:
    restart:
      enabled: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET}
    expirationMillis: ${JWT_EXPIRATION_MS}
    secureCookie: ${JWT_SECURE_COOKIE}
